### ISSUE TITLE
关于ConversationId

### ISSUE THREAD

**Issue by wwj718** [leancloud/leantodo-vue#1]
你好：）

感谢您的项目！我fork了这个项目，使用自己的leancloud账号，有一处一直卡着，想请教您

[return client.getConversation('58b8de7444d904006bee4ded')](https://github.com/leancloud/leantodo-vue/blob/master/app.js#L74)部分,我使用自己创建的Conversation id，结果`conversation.on('message'...`始终未触发 , （两个页面同时编辑时，无法实时更新），而使用您的源码是正常的，猜测是创建Conversation的参数不对

不清楚哪儿出了问题

**Comment by leeyeh** [comment]
1. 这个事先创建的 Conversation 需要是系统对话： https://leancloud.cn/docs/realtime_v2.html#系统对话
2. 需要在云引擎中部署 hook 函数在发生变化时向这个对话发送消息： https://github.com/leancloud/weapp-pay-getting-started/blob/leantodo-server/cloud.js#L87-L100

**Comment by wwj718** [comment]
@leeyeh 十分详细的回答 感谢🙏
